# Uncomment the next line to define a global platform for your project

def pod_group
  pod 'AppCoordinator',          :path => 'Modules/AppCoordinator'
  pod 'APILayer',                :path => 'Modules/APILayer'
  pod 'Core',                    :path => 'Modules/Core'
  pod 'CoreUI',                  :path => 'Modules/CoreUI'
  pod 'NewsArticle',            :path => 'Modules/NewsArticle', :testspecs => ['Tests']
  pod 'Utils',                  :path => 'Modules/Utils'
  pod 'Wormholy'
end

platform :ios, '13.0'

target 'News' do

  # Pods for News
  pod_group
  
  target 'NewsTests' do
    inherit! :search_paths
    pod_group
  end

  target 'NewsUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['DEVELOPMENT_TEAM'] = 'CHANGE YOUR TEAM ID HERE'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
  end
end
