# Uncomment the next line to define a global platform for your project

platform :ios, '13.0'

def development_pod
  pod 'AppCoordinator',		:path => 'Modules/AppCoordinator'
  pod 'APILayer',		:path => 'Modules/APILayer'
  pod 'Core',			:path => 'Modules/Core'
  pod 'CoreUI',			:path => 'Modules/CoreUI'
#  pod 'NewsArticle',		:path => 'Modules/NewsArticle', :testspecs => ['Tests']
  pod 'NewsArticle',    :path => 'Modules/NewsArticle'
  pod 'Utils',			:path => 'Modules/Utils'
  pod 'Base',     		:path => 'Modules/Base'
end

target 'News' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for News
  development_pod
  pod 'Wormholy'
  
  target 'NewsTests' do
    inherit! :search_paths
    development_pod
  end

  target 'NewsUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['DEVELOPMENT_TEAM'] = 'X26R27Y4YJ'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
  end
  

end
